name: Project Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Cache dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.OS }}-gradle-cache-${{ hashFiles('**/build.gradle') }}

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Run test
        run: ./gradlew check

      - name: Build
        run: ./gradlew build